name: Type Check

on:
    push:
        branches: develop
    pull_request:
        branches: develop

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install tox
        run: |
          python3.11 -m pip install tox
      - name: Run type checks
        run: |
            tox -e type
